name: Build, Sign & Scan PatchOpsIII

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cosign vt

      - name: Build executable
        run: |
          call env\Scripts\activate
          rmdir /S /Q dist
          rmdir /S /Q build
          del PatchOpsIII.spec
          python -m PyInstaller --onefile --noconsole --name PatchOpsIII --add-data "presets.json;." --add-data "PatchOpsIII.ico;." --icon=PatchOpsIII.ico --clean --noupx main.py

      - name: Cosign sign and scan
        run: |
          IF EXIST "dist\PatchOpsIII.exe" (
              set COSIGN_EXPERIMENTAL=1
              cosign-windows-amd64.exe login --issuer https://oauth2.sigstore.dev/auth --client-id sigstore --client-secret ""
              "%~dp0cosign-windows-amd64.exe" sign-blob -y dist\PatchOpsIII.exe
              powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 -Path 'dist\PatchOpsIII.exe').Hash" > hash.log
              set /p FILE_HASH=<hash.log
              IF DEFINED FILE_HASH (
                  echo SHA256 hash calculated: !FILE_HASH!
                  set "VT_URL=https://www.virustotal.com/gui/file/!FILE_HASH!"
                  echo VirusTotal URL: !VT_URL!
              ) ELSE (
                  echo Failed to calculate SHA256 hash.
              )
              vt scan file dist\PatchOpsIII.exe --wait --open
          ) ELSE (
              echo Executable not found! Skipping signing and scanning.
          )
